"""
Core module for NeuroSym-KG.

Contains fundamental types, interfaces, configuration, and exceptions.
"""

from neurosym_kg.core.config import (
    CacheConfig,
    Config,
    EmbeddingConfig,
    KGConfig,
    LLMConfig,
    LoggingConfig,
    get_config,
    set_config,
)
from neurosym_kg.core.exceptions import (
    ConfigurationError,
    EntityNotFoundError,
    InferenceError,
    InvalidConfigError,
    InvalidEntityError,
    InvalidReasoningStateError,
    InvalidTripleError,
    KGConnectionError,
    KGQueryError,
    KGTimeoutError,
    KnowledgeGraphError,
    LLMConnectionError,
    LLMContextLengthError,
    LLMError,
    LLMRateLimitError,
    LLMResponseError,
    LLMTimeoutError,
    MissingConfigError,
    NeuroSymError,
    NoAnswerFoundError,
    PathNotFoundError,
    ReasoningError,
    RelationNotFoundError,
    RuleParseError,
    SymbolicError,
    ValidationError,
)
from neurosym_kg.core.interfaces import (
    Cache,
    EmbeddingModel,
    EntityLinker,
    KnowledgeGraph,
    LLMBackend,
    MutableKnowledgeGraph,
    Reasoner,
    Retriever,
    StreamingLLMBackend,
    SymbolicReasoner,
)
from neurosym_kg.core.types import (
    Entity,
    EntityType,
    LLMResponse,
    Message,
    ReasoningPath,
    ReasoningResult,
    ReasoningResultStatus,
    Relation,
    RelationType,
    Subgraph,
    Triple,
)

__all__ = [
    # Types
    "Entity",
    "EntityType",
    "Relation",
    "RelationType",
    "Triple",
    "ReasoningPath",
    "Subgraph",
    "ReasoningResult",
    "ReasoningResultStatus",
    "LLMResponse",
    "Message",
    # Interfaces
    "KnowledgeGraph",
    "MutableKnowledgeGraph",
    "LLMBackend",
    "StreamingLLMBackend",
    "Reasoner",
    "EntityLinker",
    "EmbeddingModel",
    "SymbolicReasoner",
    "Retriever",
    "Cache",
    # Configuration
    "Config",
    "LLMConfig",
    "KGConfig",
    "CacheConfig",
    "EmbeddingConfig",
    "LoggingConfig",
    "get_config",
    "set_config",
    # Exceptions
    "NeuroSymError",
    "KnowledgeGraphError",
    "EntityNotFoundError",
    "RelationNotFoundError",
    "KGConnectionError",
    "KGQueryError",
    "KGTimeoutError",
    "LLMError",
    "LLMConnectionError",
    "LLMRateLimitError",
    "LLMResponseError",
    "LLMContextLengthError",
    "LLMTimeoutError",
    "ReasoningError",
    "NoAnswerFoundError",
    "PathNotFoundError",
    "InvalidReasoningStateError",
    "SymbolicError",
    "RuleParseError",
    "InferenceError",
    "ConfigurationError",
    "MissingConfigError",
    "InvalidConfigError",
    "ValidationError",
    "InvalidTripleError",
    "InvalidEntityError",
]
